---
- hosts: local
  become: false

  tasks:

    - name: Check if cluster exists
      command: k3d cluster list
      register: clusters
      changed_when: false

    - name: Create cluster
      command: >
        k3d cluster create cluster
        --agents 2
        -p "80:80@loadbalancer"
        -p "443:443@loadbalancer"
      when: "'cluster' not in clusters.stdout"
