---
- name: Configure workstation
  hosts: local
  gather_facts: true

  roles:
    # User configuration
    - git
    - ssh
    #- shell
    #- vim

    # System configuration
    - sudo
    - common
    #- docker
    #- kubectl
    #- helm
    #- terraform
    #- k3d
